--[[--
HTTP client for the Kolibre server. Uses KOReader's own bundled socket.http +
ltn12 (the same libraries KOReader's built-in kosync/OPDS code uses), not an
io.popen curl shell-out — more portable across devices, and avoids depending
on a `curl` binary being present.

Auth is a single permanent bearer token (kolibre_tok_...) generated by the
web UI when the device is registered (Impostazioni → Dispositivi → Aggiungi
Nuovo Dispositivo) — not a username/password, deliberately: a device holds a
credential of its own, revocable on its own, and never the human's.
]]

local http = require("socket.http")
local ltn12 = require("ltn12")
local socket = require("socket")
local socketutil = require("socketutil")
local JSON = require("json")
local logger = require("logger")

local KolibreApi = {}
KolibreApi.__index = KolibreApi

-- "http://192.168.1.10:8081/" -> "http://192.168.1.10:8081"
function KolibreApi.normalizeServerUrl(input)
    if not input then return nil end
    local url = input:gsub("^%s+", ""):gsub("%s+$", "")
    if url == "" then return nil end
    url = url:gsub("/+$", "")
    return url
end

function KolibreApi.new(opts)
    return setmetatable({
        server_url = opts.server_url,
        device_token = opts.device_token,
    }, KolibreApi)
end

function KolibreApi:isConfigured()
    return self.server_url ~= nil and self.server_url ~= ""
        and self.device_token ~= nil and self.device_token ~= ""
end

-- Returns decoded_body on success, or nil, err (err is a number for HTTP
-- status errors, a string for transport-level errors).
function KolibreApi:request(method, path, body)
    local sink = {}
    local request = {
        url = self.server_url .. path,
        method = method,
        sink = ltn12.sink.table(sink),
        headers = {
            ["accept"] = "application/json",
            ["Authorization"] = "Bearer " .. (self.device_token or ""),
        },
    }

    if body then
        local ok, body_json = pcall(JSON.encode, body)
        if not ok then
            return nil, "encode_error: " .. tostring(body_json)
        end
        request.source = ltn12.source.string(body_json)
        request.headers["Content-Type"] = "application/json"
        request.headers["Content-Length"] = #body_json
    end

    socketutil:set_timeout(socketutil.LARGE_BLOCK_TIMEOUT, socketutil.LARGE_TOTAL_TIMEOUT)
    local code, _, status = socket.skip(1, http.request(request))
    socketutil:reset_timeout()

    if type(code) ~= "number" then
        logger.warn("Kolibre: network error:", status or code)
        return nil, tostring(status or code or "network_error")
    end

    local decoded = nil
    if sink[1] then
        -- "simple" mode: JSON null decodes to nil, like every caller here
        -- expects. The library's default mode instead maps null to a
        -- sentinel *function* (json.util.null) to preserve null-vs-absent —
        -- a distinction nothing in this plugin cares about, and one that
        -- crashes any `if not result.field` / arithmetic check the moment a
        -- server response has an explicit `"field": null`.
        local ok, result = pcall(JSON.decode, table.concat(sink), JSON.decode.simple)
        if ok then decoded = result end
    end

    if code < 200 or code >= 300 then
        return nil, code
    end

    return decoded or {}
end

-- Streams a GET response straight to a local file (book downloads).
-- `max_bytes` (optional): aborts mid-stream once exceeded, same defense
-- BookOrbit applies specifically to its thumbnail transfers (never to real
-- book downloads, which are legitimately large) — belt-and-braces on top of
-- the server-side resize (books.py's /cover/thumbnail): even a
-- misconfigured/future oversized-image bug can't turn into an unbounded
-- decode on a memory-constrained device like a Kindle.
-- Si scarica su un file TEMPORANEO accanto alla destinazione e si rinomina
-- solo a download riuscito.
--
-- Prima si scriveva direttamente sul file vivo: `io.open(local_path, "wb")` lo
-- tronca all'istante, e su qualunque esito non-2xx — 404 compreso — un
-- `os.remove(local_path)` finiva di cancellarlo. Quindi una rete che cade a
-- meta', o un file che sul server non c'e', distruggevano il file BUONO che
-- c'era gia' sul dispositivo: un libro da riscaricare, nel caso lieve, e le
-- statistiche di lettura di anni nel caso del ripristino da backup, che
-- scrive proprio sopra statistics.sqlite3 e vocabulary_builder.sqlite3.
--
-- Rinominare e' la stessa cosa che fa gia' l'auto-aggiornamento del plugin
-- (_downloadAndInstallUpdate): o il file nuovo c'e' intero, o resta quello
-- vecchio.
function KolibreApi:downloadTo(path, local_path, max_bytes)
    local temp_path = local_path .. ".kolibre-parziale"
    local out, open_err = io.open(temp_path, "wb")
    if not out then
        return false, tostring(open_err or "open_error")
    end

    local written = 0
    -- Il sink puo' fermare il trasferimento a meta' (errore di rete, o limite
    -- di dimensione superato) mentre la risposta HTTP resta un 200: senza
    -- questo segnale il file parziale verrebbe rinominato sopra quello buono.
    local errore_sink = nil
    local sink = function(chunk, err)
        if err then
            errore_sink = tostring(err)
            out:close()
            return nil, err
        end
        if chunk == nil then
            out:close()
            return true
        end
        written = written + #chunk
        if max_bytes and written > max_bytes then
            errore_sink = "download_too_large"
            out:close()
            return nil, "download_too_large"
        end
        return out:write(chunk)
    end

    local request = {
        url = self.server_url .. path,
        method = "GET",
        sink = sink,
        headers = {
            ["Authorization"] = "Bearer " .. (self.device_token or ""),
        },
    }

    socketutil:set_timeout(socketutil.LARGE_BLOCK_TIMEOUT, socketutil.LARGE_TOTAL_TIMEOUT)
    local code, _, status = socket.skip(1, http.request(request))
    socketutil:reset_timeout()

    if errore_sink then
        os.remove(temp_path)
        return false, errore_sink
    end

    if type(code) ~= "number" or code < 200 or code >= 300 then
        -- Si cancella il PARZIALE, non la destinazione: quello che c'era
        -- prima resta dov'era.
        os.remove(temp_path)
        return false, tostring(status or code or "download_failed")
    end

    local ok_rename, rename_err = os.rename(temp_path, local_path)
    if not ok_rename then
        os.remove(temp_path)
        return false, tostring(rename_err or "rename_failed")
    end
    return true
end

-- Uploads a local file as a raw request body (no multipart) — used for
-- device backups, where server and client are both under our control and
-- there's no need for multipart/form-data's added complexity.
function KolibreApi:uploadFile(path, local_path)
    local in_file, open_err = io.open(local_path, "rb")
    if not in_file then
        return false, tostring(open_err or "open_error")
    end
    local size = in_file:seek("end")
    in_file:seek("set", 0)

    local request = {
        url = self.server_url .. path,
        method = "POST",
        source = ltn12.source.file(in_file),
        sink = ltn12.sink.table({}),
        headers = {
            ["Authorization"] = "Bearer " .. (self.device_token or ""),
            ["Content-Type"] = "application/octet-stream",
            ["Content-Length"] = tostring(size),
        },
    }

    socketutil:set_timeout(socketutil.LARGE_BLOCK_TIMEOUT, socketutil.LARGE_TOTAL_TIMEOUT)
    local code, _, status = socket.skip(1, http.request(request))
    socketutil:reset_timeout()

    if type(code) ~= "number" or code < 200 or code >= 300 then
        return false, tostring(status or code or "upload_failed")
    end
    return true
end

-- Same raw-body upload as uploadFile above, but for endpoints that answer
-- with a JSON payload the caller actually needs (identify-file's match
-- result) rather than a plain ok/fail — decodes the response the same way
-- `request` does, instead of discarding it into a sink nobody reads.
function KolibreApi:uploadFileForJson(path, local_path)
    local in_file, open_err = io.open(local_path, "rb")
    if not in_file then
        return nil, tostring(open_err or "open_error")
    end
    local size = in_file:seek("end")
    in_file:seek("set", 0)

    local sink = {}
    local request = {
        url = self.server_url .. path,
        method = "POST",
        source = ltn12.source.file(in_file),
        sink = ltn12.sink.table(sink),
        headers = {
            ["accept"] = "application/json",
            ["Authorization"] = "Bearer " .. (self.device_token or ""),
            ["Content-Type"] = "application/octet-stream",
            ["Content-Length"] = tostring(size),
        },
    }

    socketutil:set_timeout(socketutil.LARGE_BLOCK_TIMEOUT, socketutil.LARGE_TOTAL_TIMEOUT)
    local code, _, status = socket.skip(1, http.request(request))
    socketutil:reset_timeout()

    if type(code) ~= "number" then
        logger.warn("Kolibre: network error:", status or code)
        return nil, tostring(status or code or "network_error")
    end

    local decoded = nil
    if sink[1] then
        local ok, result = pcall(JSON.decode, table.concat(sink), JSON.decode.simple)
        if ok then decoded = result end
    end

    if code < 200 or code >= 300 then
        return nil, code
    end
    return decoded or {}
end

return KolibreApi
